# -*- AIRCHECQ v 0.1.2 DLeyvaPernia 2018/11/05 -*-

from PyQt5 import QtCore, QtGui, QtWidgets

from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
import matplotlib.pyplot as plt
from matplotlib.backends.backend_qt5agg import NavigationToolbar2QT


class NavigationToolbar(NavigationToolbar2QT):
    toolitems = [t for t in NavigationToolbar2QT.toolitems if
                 t[0] in ('Home', 'Pan', 'Zoom', 'Save')]


class Ui_AIRCHECQv013(object):
    def setupUi(self, AIRCHECQv013):
        AIRCHECQv013.setObjectName("AIRCHECQ 0.1.3")
        AIRCHECQv013.resize(608, 477)
        self.window = AIRCHECQv013
        self.verticalLayout = QtWidgets.QVBoxLayout(AIRCHECQv013)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(AIRCHECQv013)
        self.stackedWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.pushButton = QtWidgets.QPushButton(self.page)
        self.pushButton.setGeometry(QtCore.QRect(262, 380, 76, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.layoutWidget = QtWidgets.QWidget(self.page)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 70, 501, 301))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setTextFormat(QtCore.Qt.RichText)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setTextFormat(QtCore.Qt.RichText)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.verticalLayout_2.addWidget(self.pushButton)
        #self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        #self.label_4.setTextFormat(QtCore.Qt.RichText)
        #self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        #self.label_4.setObjectName("label_4")
        #self.verticalLayout_2.addWidget(self.label_4)
        #self.label = QtWidgets.QLabel(self.page)
        #self.label.setGeometry(QtCore.QRect(110, 240, 123, 16))
        #self.label.setObjectName("label")
        #self.lineEdit = QtWidgets.QLineEdit(self.page)
        #self.lineEdit.setGeometry(QtCore.QRect(110, 264, 381, 31))
        #self.lineEdit.setObjectName("lineEdit")
        #self.label_2 = QtWidgets.QLabel(self.page)
        #self.label_2.setGeometry(QtCore.QRect(110, 304, 63, 16))
        #self.label_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        #self.label_2.setLineWidth(-3)
        #self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        #self.label_2.setObjectName("label_2")
        #self.lineEdit_2 = QtWidgets.QLineEdit(self.page)
        #self.lineEdit_2.setGeometry(QtCore.QRect(110, 328, 381, 31))
        #self.lineEdit_2.setObjectName("lineEdit_2")
        #self.label.raise_()
        #self.lineEdit.raise_()
        #self.label_2.raise_()
        #self.lineEdit_2.raise_()
        self.layoutWidget.raise_()
        self.pushButton.raise_()
        self.stackedWidget.addWidget(self.page)

        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_7 = QtWidgets.QLabel(self.page_2)
        self.label_7.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 1, 1, 1, QtCore.Qt.AlignVCenter)
        self.tabWidget = QtWidgets.QTabWidget(self.page_2)
        self.tabWidget.setEnabled(False)
        self.tabWidget.setObjectName("tabWidget")

        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_19 = QtWidgets.QGridLayout()
        self.gridLayout_19.setSpacing(6)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.label_18 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_18.setObjectName("label_18")
        self.gridLayout_19.addWidget(self.label_18, 0, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.tab)
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_19.setObjectName("label_19")
        self.gridLayout_19.addWidget(self.label_19, 0, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_20.setObjectName("label_20")
        self.gridLayout_19.addWidget(self.label_20, 0, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.tab)
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_21.setObjectName("label_21")
        self.gridLayout_19.addWidget(self.label_21, 0, 3, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_22.setObjectName("label_22")
        self.gridLayout_19.addWidget(self.label_22, 0, 6, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.tab)
        self.label_26.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_26.setObjectName("label_26")
        self.gridLayout_19.addWidget(self.label_26, 0, 5, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_24.setObjectName("label_24")
        self.gridLayout_19.addWidget(self.label_24, 0, 4, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.tab)
        self.label_25.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_25.setObjectName("label_25")
        self.gridLayout_19.addWidget(self.label_25, 0, 7, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_19)
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.tabWidget.addTab(self.tab, "")

        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab_1)
        self.gridLayout_10.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_10.setSpacing(6)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.label_9 = QtWidgets.QLabel(self.tab_1)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_1)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 1, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.tab_1)
        self.comboBox_4.setObjectName("comboBox_4")
        self.gridLayout.addWidget(self.comboBox_4, 2, 1, 1, 1)
        self.comboBox_5 = QtWidgets.QComboBox(self.tab_1)
        self.comboBox_5.setObjectName("comboBox_5")
        self.gridLayout.addWidget(self.comboBox_5, 2, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.figure_2 = plt.figure()
        self.graphicsView_2 = FigureCanvas(self.figure_2)
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.gridLayout_6.addWidget(self.graphicsView_2, 1, 0, 1, 1)
        self.toolbar_2 = NavigationToolbar(self.graphicsView_2, self.tab_1)
        self.toolbar_2.setObjectName("toolbar_2")
        self.gridLayout_6.addWidget(self.toolbar_2, 2, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_1, "")

        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_18.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_18.setSpacing(6)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setSpacing(6)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.gridLayout_17 = QtWidgets.QGridLayout()
        self.gridLayout_17.setSpacing(6)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_16 = QtWidgets.QLabel(self.tab_4)
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_16.setObjectName("label_16")
        self.gridLayout_17.addWidget(self.label_16, 0, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tab_4)
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.gridLayout_17.addWidget(self.label_17, 0, 1, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_17.addWidget(self.checkBox, 1, 0, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_17.addWidget(self.checkBox_2, 1, 1, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_17.addWidget(self.checkBox_3, 1, 2, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_17.addWidget(self.checkBox_4, 1, 3, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout_17.addWidget(self.checkBox_5, 1, 4, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout_17.addWidget(self.checkBox_6, 1, 5, 1, 1)
        self.checkBox_7 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout_17.addWidget(self.checkBox_7, 1, 6, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_17, 0, 0, 1, 1)
        self.figure_4 = plt.figure()
        self.graphicsView_4 = FigureCanvas(self.figure_4)
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.gridLayout_16.addWidget(self.graphicsView_4, 1, 0, 1, 1)
        self.gridLayout_18.addLayout(self.gridLayout_16, 0, 0, 1, 1)
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setSpacing(6)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.toolbar_4 = NavigationToolbar(self.graphicsView_4, self.tab_4)
        self.toolbar_4.setObjectName("toolbar_4")
        self.gridLayout_15.addWidget(self.toolbar_4, 0, 0, 1, 1)
        self.gridLayout_18.addLayout(self.gridLayout_15, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")

        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_14.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_14.setSpacing(6)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setSpacing(6)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setSpacing(6)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_15 = QtWidgets.QLabel(self.tab_3)
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_15.setObjectName("label_15")
        self.gridLayout_13.addWidget(self.label_15, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab_3)
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_14.setObjectName("label_14")
        self.gridLayout_13.addWidget(self.label_14, 1, 1, 1, 1)
        self.comboBox_8 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_8.setObjectName("comboBox_8")
        self.gridLayout_13.addWidget(self.comboBox_8, 2, 0, 1, 1)
        self.comboBox_7 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_7.setObjectName("comboBox_7")
        self.gridLayout_13.addWidget(self.comboBox_7, 2, 1, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_13, 0, 0, 1, 1)


        self.gridLayout_71 = QtWidgets.QGridLayout()
        self.gridLayout_71.setSpacing(6)
        self.gridLayout_71.setObjectName("gridLayout_71")
        self.label_61 = QtWidgets.QLabel(self.tab_3)
        self.label_61.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_61.setObjectName("label_61")
        self.gridLayout_13.addWidget(self.label_61, 1, 2, 1, 1)
        self.checkBox_70 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_70.setObjectName("checkBox_70")
        self.gridLayout_71.addWidget(self.checkBox_70, 0, 0, 1, 1)
        self.checkBox_71 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_71.setObjectName("checkBox_71")
        self.gridLayout_71.addWidget(self.checkBox_71, 0, 1, 1, 1)
        self.checkBox_711 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_711.setObjectName("checkBox_711")
        self.gridLayout_71.addWidget(self.checkBox_711, 1, 1, 1, 1)
        self.checkBox_72 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_72.setObjectName("checkBox_72")
        self.gridLayout_71.addWidget(self.checkBox_72, 0, 2, 1, 1)
        self.checkBox_721 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_721.setObjectName("checkBox_721")
        self.gridLayout_71.addWidget(self.checkBox_721, 1, 2, 1, 1)
        self.checkBox_73 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_73.setObjectName("checkBox_73")
        self.gridLayout_71.addWidget(self.checkBox_73, 0, 3, 1, 1)
        self.checkBox_74 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_74.setObjectName("checkBox_74")
        self.gridLayout_71.addWidget(self.checkBox_74, 1, 3, 1, 1)
        self.checkBox_75 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_75.setObjectName("checkBox_75")
        self.gridLayout_71.addWidget(self.checkBox_75, 1, 0, 1, 1)
        self.checkBox_76 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_76.setObjectName("checkBox_76")
        self.gridLayout_71.addWidget(self.checkBox_76, 0, 4, 1, 1)
        self.checkBox_77 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_77.setObjectName("checkBox_77")
        self.gridLayout_71.addWidget(self.checkBox_77, 1, 4, 1, 1)

        self.gridLayout_13.addLayout(self.gridLayout_71, 2, 2, 1, 1)
        
        self.figure_3 = plt.figure()
        self.graphicsView_3 = FigureCanvas(self.figure_3)
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.gridLayout_12.addWidget(self.graphicsView_3, 2, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.toolbar_3 = NavigationToolbar(self.graphicsView_3, self.tab_3)
        self.toolbar_3.setObjectName("toolbar_3")
        self.gridLayout_3.addWidget(self.toolbar_3, 0, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 0, 1, 1, 1)
        self.comboBox_9 = QtWidgets.QComboBox(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_9.sizePolicy().hasHeightForWidth())
        self.comboBox_9.setSizePolicy(sizePolicy)
        self.comboBox_9.setObjectName("comboBox_9")
        self.gridLayout_3.addWidget(self.comboBox_9, 0, 2, 1, 1)
        icon_2 = QtGui.QIcon('open-folder-export.png')
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_3.setIcon(icon_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_3.addWidget(self.pushButton_3, 0, 3, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_3, 3, 0, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_12, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")

        self.gridLayout_2.addWidget(self.tabWidget, 1, 0, 1, 3)
        self.label_6 = QtWidgets.QLabel(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 1, 1, 1, QtCore.Qt.AlignVCenter)
        icon = QtGui.QIcon('open-folder-with-document.png')
        self.pushButton_2 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_2.setIcon(icon)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.page_2)
        self.label_7.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 2, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout.addWidget(self.stackedWidget)

        self.retranslateUi(AIRCHECQv013)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(AIRCHECQv013)

    def retranslateUi(self, AIRCHECQv013):
        _translate = QtCore.QCoreApplication.translate
        AIRCHECQv013.setWindowTitle(_translate("AIRCHECQ 0.1.3", "AIRCHECQ 0.1.3"))
        self.pushButton.setText(_translate("AIRCHECQ 0.1.3", "Continue"))
        self.label_3.setText(_translate("AIRCHECQ 0.1.3", "<html><head/><body><p><span style=\" font-size:24pt;\">Welcome to AIRCHECQ 0.1.3</span></p></body></html>"))
        self.label_5.setText(_translate("AIRCHECQ 0.1.3", "<html><head/><body><p align=\"justify\"><span style=\" font-style:italic;\">This software is an academic prototype, meant for internal use by the </span><a href=\"https://www.uantwerpen.be/en/projects/airchecq/\"><span style=\" font-style:italic; text-decoration: underline; color:#0000ff;\">AIRCHECQ project</span></a><span style=\" font-style:italic;\">. More information about the assessment methods applied here can be found in the PhD Thesis </span><a href=\"https://github.com/dleyva/AIRCHECQ-0.1.3/blob/master/Development%20of%20an%20Indoor%20Air%20Quality%20Index%20for%20Heritage%20Conservation%2C%20An%20Exploratory%20Study_Print.pdf\"><span style=\" font-style:italic; text-decoration: underline; color:#0000ff;\">&quot;Development of an Indoor Air Quality Index for Heritage Conservation, an Exploratory Study&quot;</span></a>.</p><p>.</p></body></html>"))
        #self.label_4.setText(_translate("AIRCHECQ 0.1.3", "Please login"))
        #self.label.setText(_translate("AIRCHECQ 0.1.3", "User name or email:"))
        #self.label_2.setText(_translate("AIRCHECQ 0.1.3", "Password:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("AIRCHECQ 0.1.3", "Data"))
        self.label_9.setText(_translate("AIRCHECQ 0.1.3", "X Axis:"))
        self.label_8.setText(_translate("AIRCHECQ 0.1.3", "Y Axis:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("AIRCHECQ 0.1.3", "Plots"))
        self.label_15.setText(_translate("AIRCHECQ 0.1.3", "Guidelines:"))
        self.label_14.setText(_translate("AIRCHECQ 0.1.3", "Materials:"))
        self.label_23.setText(_translate("AIRCHECQ 0.1.3", "Colormap:"))
        self.label_61.setText(_translate("AIRCHECQ 0.1.3", "IAQ-index:"))
        self.checkBox_70.setText(_translate("AIRCHECQ 0.1.3", "General"))
        self.checkBox_72.setText(_translate("AIRCHECQ 0.1.3", "Temperature"))
        self.checkBox_71.setText(_translate("AIRCHECQ 0.1.3", "Relative Humidity"))
        self.checkBox_721.setText(_translate("AIRCHECQ 0.1.3", "Temp. Fluct."))
        self.checkBox_711.setText(_translate("AIRCHECQ 0.1.3", "Rel. Humidity Fluct."))
        self.checkBox_73.setText(_translate("AIRCHECQ 0.1.3", "Illuminace"))
        self.checkBox_74.setText(_translate("AIRCHECQ 0.1.3", "UV"))
        self.checkBox_75.setText(_translate("AIRCHECQ 0.1.3", "PM2.5"))
        self.checkBox_76.setText(_translate("AIRCHECQ 0.1.3", "NO2"))
        self.checkBox_77.setText(_translate("AIRCHECQ 0.1.3", "O3"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("AIRCHECQ 0.1.3", "IAQ-index"))
        self.label_16.setText(_translate("AIRCHECQ 0.1.3", "Environmental Parameters:"))
        self.checkBox.setText(_translate("AIRCHECQ 0.1.3", "Temperature"))
        self.checkBox_2.setText(_translate("AIRCHECQ 0.1.3", "Relative Humidity"))
        self.checkBox_3.setText(_translate("AIRCHECQ 0.1.3", "Illuminace"))
        self.checkBox_4.setText(_translate("AIRCHECQ 0.1.3", "UV"))
        self.checkBox_5.setText(_translate("AIRCHECQ 0.1.3", "PM2.5"))
        self.checkBox_6.setText(_translate("AIRCHECQ 0.1.3", "NO2"))
        self.checkBox_7.setText(_translate("AIRCHECQ 0.1.3", "O3"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("AIRCHECQ 0.1.3", "Atypical periods"))
        self.label_6.setText(_translate("AIRCHECQ 0.1.3", "File: "))
        self.pushButton_2.setText(_translate("AIRCHECQ 0.1.3", "Load Data"))
        self.label_7.setText(_translate("AIRCHECQ 0.1.3", "<html><head/><body><p><span style=\" font-style:italic;\">Load File</span></p></body></html>"))
        self.label_18.setText(_translate("AIRCHECQ 0.1.3", "<html><head/><body><p><span style=\" font-style:italic;\">Start:</span></p></body></html>"))
        self.label_20.setText(_translate("AIRCHECQ 0.1.3", "<html><head/><body><p><span style=\" font-style:italic;\">End:</span></p></body></html>"))
        self.label_22.setText(_translate("AIRCHECQ 0.1.3", "<html><head/><body><p><span style=\" font-style:italic;\">Time between inputs (minutes):</span></p></body></html>"))
        self.label_24.setText(_translate("AIRCHECQ 0.1.3", "<html><head/><body><p><span style=\" font-style:italic;\">Number of inputs:</span></p></body></html>"))
        self.pushButton_3.setText(_translate("AIRCHECQ 0.1.3", "Export Data"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AIRCHECQv013 = QtWidgets.QWidget()
    ui = Ui_AIRCHECQv013()
    ui.setupUi(AIRCHECQv013)
    AIRCHECQv013.show()
    sys.exit(app.exec_())

